import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import CollectionPage from "./collection/[page]";

import { api } from "~/utils/api";
import { useState } from "react";

const Home: NextPage = () => {
  const [ loggedInUsername, setLoggedInUsername ] = useState("");
  return (
    <>
      <Head>
        <title>Trove</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
            <Link href="/collection/1">1</Link>
      </main>
    </>
  );
};

export default Home;
