import { type NextPage } from "next";
import Head from "next/head";
// import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { useState } from "react";
import router from "next/router";

const Home: NextPage = () => {
  const [loggedInUsername, setLoggedInUsername] = useState("");
  return (
    <>
      <Head>
        <title>Trove</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link href="../styles/global.css" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <label htmlFor="discogs-collection-search">Fake Login</label>
        <input
          type="search"
          id="discogs-collection-search"
          onChange={(event) => setLoggedInUsername(event.target.value)}
        />
        <button
          onClick={() => {
            router.push({
              pathname: "/user/[name]/collectionSearch",
              query: { name: loggedInUsername },
            });
          }}
        >
          Login
        </button>
      </main>
    </>
  );
};

export default Home;
